version: "3.3"

services:

  influxdb:
    image: influxdb:1.8.4
    environment:
      - INFLUXDB_DB=devops
    volumes:
      - ./influx/influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - 8086:8086  

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_INSTALL_PLUGINS=aceiot-svg-panel
    depends_on:
      - influxdb

  strapi:
    image: strapi/strapi
    volumes:
      - ./strapi:/srv/app
    ports:
      - 1337:1337

  metrics-service:
    build: ./metrics-service
    environment:
      - INFLUXDB=http://xxx:yyyy@influxdb:8086/devops
      - STRAPI_URL=http://strapi:1337
      - STRAPI_USERNAME=api
      - STRAPI_PASSWORD=techmetrics
      - CRON=0 0 18 * * *
      - GALAXY_HOST=https://galaxyops-svc.ciandt.com
    depends_on:
      - influxdb
      - strapi
    restart: always

  db-transformation-service:
    build: ./db-transformation-service
    environment:
      - INFLUXDB=http://xxx:yyyy@influxdb:8086/devops
      - STRAPI_URL=http://strapi:1337
      - STRAPI_USERNAME=api
      - STRAPI_PASSWORD=techmetrics
      - CRON=0 0 11 * * *
    depends_on:
      - influxdb
      - strapi
    restart: always 
